---
# tasks file for terraform
- include_role:
    name: andrewrothstein.unarchivedeps

- name: check for {{ terraform_installed_exe }}
  stat:
    path: '{{ terraform_installed_exe }}'
  changed_when: false
  register: terraform_binary

- when: not terraform_binary.stat.exists
  block:
    - name: get checksums={{ terraform_checksum_url }}
      uri:
        url: '{{ terraform_checksum_url }}'
        return_content: yes
      register: terraform_checksum_response

    - name: resolve checksum for {{ terraform_archive }}
      set_fact:
        terraform_checksum: "{{ terraform_checksum_algo }}:{{ item.split()[0] }}"
      loop: "{{ terraform_checksum_response.content.split('\n') }}"
      when: terraform_archive in item

    - name: download={{ terraform_download_url }}, dest={{ terraform_tmp_zip }}
      become: '{{ terraform_become }}'
      become_user: root
      become_method: sudo
      get_url:
        url: '{{ terraform_download_url }}'
        dest: '{{ terraform_tmp_zip }}'
        checksum: '{{ terraform_checksum }}'
        mode: '0644'

    - name: mkdir={{ terraform_install_dir }}
      become: '{{ terraform_become }}'
      become_user: root
      become_method: sudo
      file:
        path: '{{ terraform_install_dir }}'
        state: directory
        mode: '0755'

    - name: unarchive={{ terraform_tmp_zip }}, dest={{ terraform_install_dir }}
      become: '{{ terraform_become }}'
      become_user: root
      become_method: sudo
      unarchive:
        remote_src: true
        src: '{{ terraform_tmp_zip }}'
        dest: '{{ terraform_install_dir }}'
        creates: '{{ terraform_installed_exe }}'
        mode: '0755'
  always:
    - name: rm {{ terraform_tmp_zip }}
      become: '{{ terraform_become }}'
      become_user: root
      become_method: sudo
      file:
        path: '{{ terraform_tmp_zip }}'
        state: absent

- name: mkdir={{ terraform_link_dir }}
  become: '{{ terraform_become }}'
  become_user: root
  become_method: sudo
  file:
    path: '{{ terraform_link_dir }}'
    state: directory
    mode: '0755'

- name: link {{ terraform_installed_link }} to {{ terraform_installed_exe }}
  become: '{{ terraform_become }}'
  become_user: root
  become_method: sudo
  file:
    src: '{{ terraform_installed_exe }}'
    dest: '{{ terraform_installed_link }}'
    state: link
    force: true
